-- +goose Up
-- SKY-414: durable, DB-backed event queue for the router. See the SQLite
-- sibling (202606020001_event_queue.sql) for the full rationale: the
-- in-memory bus drops events for slow subscribers under burst, and the
-- router — which persists event rows and creates tasks — must not lose
-- work that way. The events audit row and a queue row are written
-- atomically at ingest (transactional outbox) and the router drains the
-- queue with claim semantics.
--
-- Postgres adds D3 multi-tenant conventions: uuid org_id, composite
-- (col, org_id) FKs against the (id, org_id) unique keys on events /
-- entities, RLS, and tf_app grants. ClaimNext uses FOR UPDATE SKIP
-- LOCKED so multiple router workers can drain concurrently without
-- double-processing — groundwork for horizontal routing (running N
-- workers is a SKY-414 non-goal). Wired against the admin pool: the
-- ingestor and drain worker are system services with no JWT-claims
-- context, so the RLS policy below is defense-in-depth (admin bypasses
-- it) and org_id stays bound in every statement.
CREATE TABLE public.event_queue (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id       uuid NOT NULL,
    event_id     uuid NOT NULL,
    entity_id    uuid,
    event_type   text NOT NULL,
    status       text NOT NULL DEFAULT 'pending',
    attempts     integer NOT NULL DEFAULT 0,
    last_error   text,
    enqueued_at  timestamp with time zone NOT NULL DEFAULT now(),
    claimed_at   timestamp with time zone,
    processed_at timestamp with time zone
);

ALTER TABLE ONLY public.event_queue
    ADD CONSTRAINT event_queue_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.orgs(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.event_queue
    ADD CONSTRAINT event_queue_event_id_org_id_fkey FOREIGN KEY (event_id, org_id) REFERENCES public.events(id, org_id) ON DELETE CASCADE;
ALTER TABLE ONLY public.event_queue
    ADD CONSTRAINT event_queue_entity_id_org_id_fkey FOREIGN KEY (entity_id, org_id) REFERENCES public.entities(id, org_id) ON DELETE CASCADE;

-- FIFO drain over pending rows: the worker claims the oldest by id.
CREATE INDEX idx_event_queue_pending ON public.event_queue USING btree (id) WHERE (status = 'pending'::text);
-- Per-entity history for debug/audit + the entity-scoped reads.
CREATE INDEX idx_event_queue_entity ON public.event_queue USING btree (entity_id);
-- Retention prune of done rows + ops visibility by terminal state/time.
CREATE INDEX idx_event_queue_status_processed ON public.event_queue USING btree (status, processed_at);
-- One queue row per event row — the outbox invariant + idempotent enqueue.
CREATE UNIQUE INDEX idx_event_queue_event ON public.event_queue USING btree (event_id);

ALTER TABLE public.event_queue ENABLE ROW LEVEL SECURITY;
CREATE POLICY event_queue_all ON public.event_queue USING (((org_id = tf.current_org_id()) AND tf.user_has_org_access(org_id))) WITH CHECK (((org_id = tf.current_org_id()) AND tf.user_has_org_access(org_id)));

GRANT ALL ON TABLE public.event_queue TO postgres;
GRANT ALL ON TABLE public.event_queue TO anon;
GRANT ALL ON TABLE public.event_queue TO authenticated;
GRANT ALL ON TABLE public.event_queue TO service_role;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.event_queue TO tf_app;

-- +goose Down
SELECT 'down not supported';
