// Package workitemtest is the conformance suite for the shared work-item
// contract. It runs against a fixture table it creates itself, so the contract
// is provable before any production table adopts it — and so a dialect's
// answer to a crash, a takeover or a cancellation race is asserted rather than
// assumed to match its twin.
//
// One test file per dialect invokes Run, the same shape as every dbtest
// conformance pair. The fixture tables are test-only and must never appear in
// a production schema. RunTable is the table-agnostic half of the same suite,
// which each adopting production table invokes against itself with the Kind
// it declares.
package workitemtest

import (
	"context"
	"database/sql"
	"fmt"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/sky-ai-eng/triage-factory/internal/db/workitem"
)

// Factory hands the suite a connection, the dialect behind it, and an org id
// to scope rows to. It is called once per subtest: SQLite opens a fresh
// in-memory database, Postgres resets the shared container and mints a new org.
type Factory func(t *testing.T) (conn *sql.DB, dialect workitem.Dialect, orgID string)

// TableFactory hands RunTable a connection, the adopting Kind as production
// declares it, an org to scope rows to, and a way to mint valid values for
// the kind's own columns: cols(i) returns the column map for the i-th
// admission in a subtest, and may insert whatever parent rows a foreign key
// needs (an events row, an entity row).
type TableFactory func(t *testing.T) (conn *sql.DB, kind workitem.Kind, orgID string, cols func(i int) map[string]any)

// The two fixture tables, one per uniqueness mode with an index. UniqueNone
// needs no table of its own: it declares no index, so it is exercised on the
// unsettled table with unkeyed admissions, which is the only way a UniqueNone
// kind may be called at all.
const (
	FixtureTable        = "workitem_fixture"
	FixtureForeverTable = "workitem_fixture_forever"
)

// FixtureDDL is the fixture schema: both tables dropped and recreated, then
// every index IndexDDL renders for them. The drop matters on Postgres, where
// the shared harness truncates the tables it knows about and these are not
// among them.
func FixtureDDL(dialect workitem.Dialect) []string {
	var out []string
	for _, spec := range []struct {
		table  string
		unique workitem.UniqueMode
	}{
		{FixtureTable, workitem.UniqueWhileUnsettled},
		{FixtureForeverTable, workitem.UniqueForever},
	} {
		out = append(out, TableDDL(dialect, spec.table, spec.unique)...)
	}
	return out
}

// TableDDL drops and recreates one fixture-shaped table with the indexes its
// uniqueness mode calls for. A dialect's own test file reaches for this when it
// needs the same column block under different governance — a copy carrying RLS
// policies, say — rather than restating the shape and letting the two drift.
func TableDDL(dialect workitem.Dialect, table string, unique workitem.UniqueMode) []string {
	return append([]string{
		"DROP TABLE IF EXISTS " + table,
		createFixtureTable(dialect, table),
	}, workitem.IndexDDL(workitem.Kind{
		Table: table, Dialect: dialect, Unique: unique,
		Strategy: workitem.SingleTx,
	})...)
}

// createFixtureTable is the shared column block in each dialect's spelling,
// plus the two kind columns the suite uses: payload as a domain write's target
// and frozen_col as the value a receipt freezes at claim.
func createFixtureTable(dialect workitem.Dialect, table string) string {
	if dialect == workitem.Postgres {
		return `CREATE TABLE ` + table + ` (
			id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			org_id               uuid NOT NULL,
			status               TEXT NOT NULL CHECK (status IN ('ready','leased','done','parked','cancelled')),
			attempt              INTEGER NOT NULL DEFAULT 0,
			max_attempts         INTEGER NOT NULL,
			next_attempt_at      TIMESTAMPTZ NULL,
			lease_generation     BIGINT NOT NULL DEFAULT 0,
			lease_owner          TEXT NULL,
			lease_epoch          BIGINT NULL,
			leased_at            TIMESTAMPTZ NULL,
			lease_expires_at     TIMESTAMPTZ NULL,
			cancel_requested_at  TIMESTAMPTZ NULL,
			cancel_requested_by  TEXT NULL,
			cancel_reason        TEXT NULL,
			last_error           TEXT NULL,
			last_outcome         TEXT NULL,
			unique_key           TEXT NULL,
			superseded_by        BIGINT NULL,
			first_enqueued_at    TIMESTAMPTZ NOT NULL,
			created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
			done_at              TIMESTAMPTZ NULL,
			payload              TEXT,
			frozen_col           INTEGER
		)`
	}
	return `CREATE TABLE ` + table + ` (
		id                   INTEGER PRIMARY KEY AUTOINCREMENT,
		org_id               TEXT NOT NULL,
		status               TEXT NOT NULL CHECK (status IN ('ready','leased','done','parked','cancelled')),
		attempt              INTEGER NOT NULL DEFAULT 0,
		max_attempts         INTEGER NOT NULL,
		next_attempt_at      TEXT NULL,
		lease_generation     INTEGER NOT NULL DEFAULT 0,
		lease_owner          TEXT NULL,
		lease_epoch          INTEGER NULL,
		leased_at            TEXT NULL,
		lease_expires_at     TEXT NULL,
		cancel_requested_at  TEXT NULL,
		cancel_requested_by  TEXT NULL,
		cancel_reason        TEXT NULL,
		last_error           TEXT NULL,
		last_outcome         TEXT NULL,
		unique_key           TEXT NULL,
		superseded_by        INTEGER NULL,
		first_enqueued_at    TEXT NOT NULL,
		created_at           TEXT NOT NULL,
		done_at              TEXT NULL,
		payload              TEXT,
		frozen_col           INTEGER
	)`
}

// env is one subtest's world: a connection, the org its rows live in, the
// Kind under test, and the hook that mints each admission's own columns.
type env struct {
	t       *testing.T
	ctx     context.Context
	conn    *sql.DB
	dialect workitem.Dialect
	org     string
	kind    workitem.Kind
	// cols mints the kind's own columns for the i-th admission; admissions
	// counts them. The fixture's hook hands back payload/frozen_col; a
	// production table's hook inserts whatever its foreign keys need.
	cols       func(i int) map[string]any
	admissions int
	// fixture marks the suite's own tables, whose payload column the
	// domain-write closures target. A production table has no such column,
	// so those closures are no-ops there.
	fixture bool
}

// envFactory builds one subtest's env under a policy. Run and RunTable each
// supply one, which is how a subtest that reads and writes only the shared
// block runs unchanged over the fixture and over a production table.
type envFactory func(t *testing.T, policy workitem.Policy) *env

// opts is what a subtest varies about its fixture Kind.
type opts struct {
	table    string
	unique   workitem.UniqueMode
	strategy workitem.Strategy
	policy   workitem.Policy
}

// shortLease is the lease crash simulation runs on: long enough that a
// deliberate operation inside it is not racing expiry, short enough that
// waiting past it costs a test a fraction of a second.
const shortLease = 300 * time.Millisecond

// fastBackoff keeps a requeued row claimable again immediately, so a budget
// test spends its time on attempts rather than on backoff.
var fastBackoff = workitem.BackoffSpec{Base: time.Millisecond, Cap: time.Millisecond, Jitter: 0.1}

func setup(t *testing.T, mk Factory, o opts) *env {
	t.Helper()
	conn, dialect, org := mk(t)
	e := &env{t: t, ctx: t.Context(), conn: conn, dialect: dialect, org: org, fixture: true}
	for _, stmt := range FixtureDDL(dialect) {
		if _, err := conn.ExecContext(e.ctx, stmt); err != nil {
			t.Fatalf("fixture DDL %q: %v", firstLine(stmt), err)
		}
	}
	if o.table == "" {
		o.table = FixtureTable
	}
	if o.strategy == workitem.StrategyUnset {
		o.strategy = workitem.SingleTx
	}
	e.kind = workitem.Kind{
		Table:    o.table,
		Dialect:  dialect,
		Policy:   o.policy,
		Unique:   o.unique,
		Strategy: o.strategy,
		Columns:  []string{"payload", "frozen_col"},
		Frozen:   []string{"frozen_col"},
	}
	e.cols = func(int) map[string]any { return map[string]any{"payload": "p", "frozen_col": 0} }
	if err := e.kind.Validate(); err != nil {
		t.Fatalf("fixture kind: %v", err)
	}
	return e
}

// setupTable is setup for a production table: the factory's Kind, with the
// policy swapped for the subtest's so production timing never enters a test.
// Uniqueness mode, strategy and columns stay as declared, because those are
// what the subtest is conforming.
func setupTable(t *testing.T, mk TableFactory, policy workitem.Policy) *env {
	t.Helper()
	conn, kind, org, cols := mk(t)
	kind.Policy = policy
	if err := kind.Validate(); err != nil {
		t.Fatalf("table kind: %v", err)
	}
	return &env{t: t, ctx: t.Context(), conn: conn, dialect: kind.Dialect, org: org, kind: kind, cols: cols}
}

// nextCols mints the next admission's columns through the hook.
func (e *env) nextCols() map[string]any {
	cols := e.cols(e.admissions)
	e.admissions++
	return cols
}

// key is the unique key an admission carries: the name as given, or none for
// a kind that dedups nothing and would refuse one.
func (e *env) key(name string) string {
	if e.kind.Unique == workitem.UniqueNone {
		return ""
	}
	return name
}

// withKind returns the same world seen through a differently-declared Kind,
// for the assertions that need both completion strategies over one table.
func (e *env) withKind(mutate func(*workitem.Kind)) *env {
	clone := *e
	k := e.kind
	mutate(&k)
	clone.kind = k
	return &clone
}

// q rewrites the suite's `?` placeholders into the dialect's, so a test can
// write one query.
func (e *env) q(query string) string {
	if e.dialect != workitem.Postgres {
		return query
	}
	var b strings.Builder
	n := 0
	for _, r := range query {
		if r == '?' {
			n++
			b.WriteString("$" + strconv.Itoa(n))
			continue
		}
		b.WriteRune(r)
	}
	return b.String()
}

// pastExpr is a timestamp an hour in the past, in the dialect's storage shape.
// Tests use it to age a lease without waiting for one.
func (e *env) pastExpr() string {
	if e.dialect == workitem.Postgres {
		return "clock_timestamp() - interval '1 hour'"
	}
	return `strftime('%Y-%m-%d %H:%M:%f','now','-1 hours')`
}

func (e *env) exec(query string, args ...any) {
	e.t.Helper()
	if _, err := e.conn.ExecContext(e.ctx, e.q(query), args...); err != nil {
		e.t.Fatalf("exec %q: %v", firstLine(query), err)
	}
}

// admit inserts a ready row under key, its own columns drawn from the hook,
// and fails the test on anything but a clean insert.
func (e *env) admit(key string) int64 {
	e.t.Helper()
	return e.admitCols(e.org, e.key(key), e.nextCols())
}

// admitWith is admit with the fixture's own columns chosen by the test, for
// the assertions that read a payload back or freeze a specific value.
func (e *env) admitWith(key, payload string, frozen int) int64 {
	e.t.Helper()
	e.admissions++
	return e.admitCols(e.org, key, map[string]any{"payload": payload, "frozen_col": frozen})
}

// admitIn admits into an org other than the subtest's own, for the
// cross-tenant assertions.
func (e *env) admitIn(org, key string) int64 {
	e.t.Helper()
	return e.admitCols(org, key, e.nextCols())
}

func (e *env) admitCols(org, key string, cols map[string]any) int64 {
	e.t.Helper()
	id, dup, err := workitem.Admit(e.ctx, e.conn, e.kind, org, key, cols)
	if err != nil {
		e.t.Fatalf("admit %q in %s: %v", key, org, err)
	}
	if dup {
		e.t.Fatalf("admit %q in %s: deduplicated against an existing row", key, org)
	}
	return id
}

// claim runs one Claim scoped to the subtest's org and fails on error.
func (e *env) claim(owner workitem.Owner, n int) workitem.ClaimResult {
	e.t.Helper()
	return e.claimIn(owner, e.org, n)
}

// claimIn runs one Claim against a chosen org scope; "" is every org.
func (e *env) claimIn(owner workitem.Owner, orgID string, n int) workitem.ClaimResult {
	e.t.Helper()
	res, err := workitem.Claim(e.ctx, e.conn, e.kind, owner, orgID, n)
	if err != nil {
		e.t.Fatalf("claim: %v", err)
	}
	return res
}

// requireStatus asserts one row's status.
func (e *env) requireStatus(id int64, want string) {
	e.t.Helper()
	if got := asString(e.row(id)["status"]); got != want {
		e.t.Fatalf("row %d status = %q, want %q", id, got, want)
	}
}

// requireLeaseCleared asserts every lease column on a row is released, which
// is what makes "parked" and "somebody is driving this" disjoint.
func (e *env) requireLeaseCleared(id int64) {
	e.t.Helper()
	r := e.row(id)
	for _, col := range []string{"lease_owner", "lease_epoch", "leased_at", "lease_expires_at"} {
		if r[col] != nil {
			e.t.Errorf("row %d %s = %v, want NULL", id, col, r[col])
		}
	}
}

// claimOne claims exactly one row and returns its receipt.
func (e *env) claimOne(ownerID string, epoch int64) workitem.Receipt {
	e.t.Helper()
	res := e.claim(workitem.Owner{ID: ownerID, Epoch: epoch}, 1)
	if len(res.Claimed) != 1 {
		e.t.Fatalf("claimOne: got %d receipts (cancelled=%d parked=%d)", len(res.Claimed), res.Cancelled, res.Parked)
	}
	return res.Claimed[0]
}

// expireLease waits past the kind's lease, which is how the suite spells a
// worker dying with no terminal write.
func (e *env) expireLease() {
	e.t.Helper()
	lease := e.kind.Policy.Lease
	if lease <= 0 {
		e.t.Fatal("expireLease needs an explicit short lease")
	}
	time.Sleep(lease + 150*time.Millisecond)
}

// row reads every column of one row, normalized so the two dialects' drivers
// compare equal.
func (e *env) row(id int64) map[string]any {
	e.t.Helper()
	for _, r := range e.table() {
		if asInt(r["id"]) == id {
			return r
		}
	}
	e.t.Fatalf("row %d not found", id)
	return nil
}

// table reads the whole fixture table, every column, ordered by id. It is what
// the straggler assertions compare before and after: not "the row I expected
// did not change", but "nothing changed at all".
func (e *env) table() []map[string]any {
	e.t.Helper()
	rows, err := e.conn.QueryContext(e.ctx, "SELECT * FROM "+e.kind.Table+" ORDER BY id")
	if err != nil {
		e.t.Fatalf("read table: %v", err)
	}
	defer rows.Close()
	cols, err := rows.Columns()
	if err != nil {
		e.t.Fatalf("columns: %v", err)
	}
	var out []map[string]any
	for rows.Next() {
		cells := make([]any, len(cols))
		dest := make([]any, len(cols))
		for i := range cells {
			dest[i] = &cells[i]
		}
		if err := rows.Scan(dest...); err != nil {
			e.t.Fatalf("scan: %v", err)
		}
		rec := make(map[string]any, len(cols))
		for i, c := range cols {
			rec[c] = normalize(cells[i])
		}
		out = append(out, rec)
	}
	if err := rows.Err(); err != nil {
		e.t.Fatalf("read table: %v", err)
	}
	return out
}

// normalize collapses the driver shapes that differ between dialects for the
// same stored value, so a snapshot comparison tests the data and not the
// driver.
func normalize(v any) any {
	switch t := v.(type) {
	case nil:
		return nil
	case []byte:
		return string(t)
	case time.Time:
		return t.UTC().Format(time.RFC3339Nano)
	case int32:
		return int64(t)
	case int:
		return int64(t)
	default:
		return v
	}
}

func asInt(v any) int64 {
	switch t := v.(type) {
	case int64:
		return t
	case int32:
		return int64(t)
	case int:
		return int64(t)
	case float64:
		return int64(t)
	case string:
		n, _ := strconv.ParseInt(t, 10, 64)
		return n
	default:
		return 0
	}
}

func asString(v any) string {
	if v == nil {
		return ""
	}
	if s, ok := v.(string); ok {
		return s
	}
	return fmt.Sprint(v)
}

func firstLine(s string) string {
	s = strings.TrimSpace(s)
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[:i] + " …"
	}
	return s
}
