package main

import "testing"

func TestClassifyPath(t *testing.T) {
	cases := []struct {
		path string
		want fileClass
	}{
		{"internal/routing/router.go", classCode},
		{"main.go", classCode},
		{"frontend/src/components/AgentCard.tsx", classCode},
		{"internal/db/migrations-sqlite/202605130001_baseline.sql", classCode},
		{"internal/agentprompt/blocks/identity/machinist.txt", classCode},
		{".github/workflows/test.yml", classCode},
		{"scripts/lint.sh", classCode},

		{"internal/routing/router_test.go", classTests},
		{"frontend/src/components/AgentCard.test.tsx", classTests},
		{"frontend/src/hooks/useConversationDetail.spec.ts", classTests},
		{"internal/db/dbtest/conformance.go", classTests},
		{"internal/db/pgtest/harness.go", classTests},
		{"harness/tf-harness-tools/tests/parity.rs", classTests},
		{"internal/tracker/testdata/pr.json", classTests},

		{"README.md", classDocs},
		{"docs/concepts/tracked-events.md", classDocs},
		{"docs/for-agents/specs/sky-261-d-claims.html", classDocs},
		{"LICENSE", classDocs},
		{"CHANGELOG.md", classDocs},

		{"go.sum", classGenerated},
		{"frontend/pnpm-lock.yaml", classGenerated},
		{"harness/Cargo.lock", classGenerated},
		{"internal/agentproc/package-lock.json", classGenerated},
		{"vendor/github.com/x/y/z.go", classGenerated},
	}
	for _, tc := range cases {
		if got := classifyPath(tc.path); got != tc.want {
			t.Errorf("classifyPath(%q) = %v, want %v", tc.path, got, tc.want)
		}
	}
}

func TestDocsBeatsTestsForDocPaths(t *testing.T) {
	// A spec under docs/ that happens to sit next to a fixture directory is
	// still documentation; the docs rule runs first for exactly this reason.
	if got := classifyPath("docs/for-agents/specs/sky-254-runsc-validation/tests/notes.md"); got != classDocs {
		t.Errorf("got %v, want documentation", got)
	}
}

func TestIsGeneratedContent(t *testing.T) {
	if !isGeneratedContent([]byte("// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage p\n")) {
		t.Error("did not detect the Go generated-file marker")
	}
	if isGeneratedContent([]byte("package p\n\n// Code generated output is parsed here. DO NOT EDIT. is a marker.\n")) {
		// The marker has to be the whole line, not a mention of it in prose.
		t.Error("false positive on prose mentioning the marker")
	}
	if isGeneratedContent([]byte("package p\n")) {
		t.Error("false positive on an ordinary file")
	}
}
