// Package agentmeta builds the disclosure footer appended to everything an
// agent publishes in a human's name — pull request bodies and review bodies —
// and the deep link that footer carries. A reader on GitHub learns two things
// from it: that an agent wrote the text above, and where the run that wrote it
// lives.
//
// The footer is static: it depends on nothing that changes while the run is
// still going, which is what lets it be appended at creation rather than at
// some later settling point. Anything live about a run — its spend, its
// elapsed time, the model it ran on — belongs on the run page the link points
// at, where it can keep moving after the body has been published.
package agentmeta

import (
	"fmt"

	"github.com/sky-ai-eng/triage-factory/internal/runmode"
)

// Build returns the markdown footer for an agent-authored body. kind is the
// noun in the disclosure ("PR", "review"). runURL is the run's deep link from
// RunURL; empty omits the link line rather than fabricating one, which is what
// a deployment with no public URL configured gets. The result always begins
// with a blank line and a rule, so the caller concatenates body + Build(...).
func Build(kind, runURL string) string {
	footer := fmt.Sprintf(
		"\n\n---\n*This %s was partially generated by AI using [Triage Factory](https://github.com/sky-ai-eng/triage-factory).*",
		kind,
	)
	if runURL != "" {
		footer += "\n\n[View the run](" + runURL + ")"
	}
	return footer
}

// RunURL is the deep link to a run in the TF UI, the value both the
// {{RUN_URL}} prompt placeholder and the footer's link resolve to. publicURL
// is the deployment's externally-visible base with no trailing slash; empty
// yields "" — never a fabricated localhost link for a deployment that has not
// said where it lives. Local mode's run route has no org segment
// (frontend/src/main.tsx "/runs/:conversationID"); multi mode nests every
// route under "/orgs/:org_id".
func RunURL(publicURL, orgID, conversationID string) string {
	if publicURL == "" {
		return ""
	}
	if runmode.Current() == runmode.ModeMulti {
		return publicURL + "/orgs/" + orgID + "/runs/" + conversationID
	}
	return publicURL + "/runs/" + conversationID
}
