// Package agentmeta builds the disclosure / metadata footer appended
// to agent-published content (review bodies, PR bodies, future surfaces
// like issue comments). Consolidates what used to live as two near-
// duplicate builders in cmd/exec/gh/pr.go and internal/server/
// reviews_handler.go — both did the same job (compute elapsed + cost,
// render markdown footer) but disagreed on the cost source.
//
// The footer discloses Time + Cost only — no model name. A multi-step
// blueprint may run several different models across its steps, so a
// single "Model:" line would be a half-truth (it would name only the
// step that authored the published review/PR); dropping it is the
// honest answer.
//
// Cost is summed across every step of the blueprint run, not just
// the step that authored the content. The authoring conversation's own cost is
// derived at read time as the SUM of the messages ledger's cost_usd
// stamps (the standard path), falling back to a token-estimate from
// TokenTotalsSystem only while nothing has settled — the still-running
// standalone CLI case. The sibling steps' settled costs are added on
// top via BlueprintSiblingCostUSDSystem. With the queue-then-approve
// flow, review/PR submit run AFTER the agent has terminated, so the
// authoring conversation's ledger has settled and the estimate fallback is
// rare.
package agentmeta

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/sky-ai-eng/triage-factory/internal/ai"
	"github.com/sky-ai-eng/triage-factory/internal/db"
	"github.com/sky-ai-eng/triage-factory/internal/domain"
)

// footerSeparator introduces every footer Build emits; the caller concatenates
// `body + Build(...)`, so it doubles as the cut point for StripFooter.
const footerSeparator = "\n\n---\n"

// footerDisclaimerMarker is the kind-independent substring present in every
// footer Build emits (the disclaimer renders "*This <kind> was partially
// generated by AI using [Triage Factory]...*"). StripFooter keys on it so it
// recognizes a footer regardless of the kind it was built for.
const footerDisclaimerMarker = "partially generated by AI using [Triage Factory]"

// Build returns the markdown footer to append to an agent-authored
// body. kind is the noun in the disclaimer ("review", "PR", future
// surfaces). Always begins with "\n\n---\n" so the caller just
// concatenates: `body + agentmeta.Build(...)`.
//
// Empty conversationID returns an empty string — there's nothing to disclose
// when no agent conversation is associated with the content. Callers safely
// concatenate the result; a human running the CLI directly (no
// delegation context) gets their body back unmodified instead of a
// "This was partially generated by AI" lie.
//
// On DB lookup failure with a non-empty conversationID we fall back to the
// bare branding-only footer rather than blocking the submit — the
// disclosure is still meaningful (a conversation did exist) even if we
// couldn't render the metrics.
//
// Reads route through the admin-pool `...System` variants.
// Build is a pure read-only formatting utility invoked from contexts
// that don't carry JWT claims — the cmd/exec agent subcommands
// (review/PR submit) and the server's post-approval cleanup paths.
// Wrapping the two-row read in its own synthetic-claims tx just to
// satisfy RLS for a footer would be tx-machinery overhead with no
// visibility benefit (the agent has already proven it can act as
// this conversation via TRIAGE_FACTORY_CONVERSATION_ID → ResolveConversationIdentity, and the
// server path is system-driven).
func Build(conversations db.ConversationStore, orgID, conversationID, kind string) string {
	if conversationID == "" {
		return ""
	}

	disclaimer := fmt.Sprintf(
		"*This %s was partially generated by AI using [Triage Factory](https://github.com/sky-ai-eng/triage-factory).*",
		kind,
	)
	bare := "\n\n---\n" + disclaimer

	ctx := context.Background()
	conv, err := conversations.GetSystem(ctx, orgID, conversationID)
	if err != nil || conv == nil {
		return bare
	}

	elapsed := elapsedFromConversation(ctx, conversations, orgID, conversationID, conv)
	cost, costPrefix := costFromConversation(ctx, conversations, orgID, conversationID, conv)

	return fmt.Sprintf(
		"\n\n---\n%s\n\nTime: %s | Cost: %s$%.3f",
		disclaimer, elapsed, costPrefix, cost,
	)
}

// StripFooter removes a footer block previously appended by Build so that
// re-appending is idempotent — an approval retried after a partial GitHub
// failure must not stack a second footer onto the PR body. It cuts from the
// footerSeparator that introduces the disclaimer; a body with no recognizable
// footer is returned unchanged. If somehow stacked already (a pre-fix double),
// cutting at the first footer removes all of them, so a fresh append leaves
// exactly one. The marker requires both the separator and the disclaimer text,
// so ordinary "---" rules in user content aren't mistaken for a footer.
//
// Assumption: a body that contains footerDisclaimerMarker verbatim above a
// "\n\n---\n" separator (e.g. an agent quoting a footer inside its own
// description) would have the content above that point stripped. The practical
// risk is negligible — nobody writes this exact phrase intentionally in a PR
// body — so we accept it rather than carry a more elaborate (and equally
// heuristic) footer fingerprint.
func StripFooter(body string) string {
	marker := strings.Index(body, footerDisclaimerMarker)
	if marker < 0 {
		return body
	}
	sep := strings.LastIndex(body[:marker], footerSeparator)
	if sep < 0 {
		return body
	}
	return body[:sep]
}

// elapsedFromConversation returns the human-readable total time across the
// conversation's whole blueprint run: its own elapsed time plus the settled
// duration of every sibling step in the same blueprint_run. This is the
// time analog of costFromConversation — a published review/PR discloses the total
// time the multi-step blueprint spent, not just the step that authored
// it. Steps run sequentially, so summed per-step durations read as the
// blueprint's working time. Sibling steps are all terminal by the time a
// footer is built, so their duration_ms is settled; a failed sibling read
// just omits their contribution rather than blocking the submit.
//
// "?" only on a conversation with no own duration AND no StartedAt, which
// shouldn't happen in practice.
func elapsedFromConversation(ctx context.Context, conversations db.ConversationStore, orgID, conversationID string, conv *domain.Conversation) string {
	own, ok := ownDurationMs(conv)
	if !ok {
		return "?"
	}
	total := own
	if conv.BlueprintRunID != "" {
		if siblings, err := conversations.BlueprintSiblingDurationMsSystem(ctx, orgID, conv.BlueprintRunID, conversationID); err == nil {
			total += siblings
		}
	}
	return prettyDurationMs(total)
}

// ownDurationMs resolves a single conversation's own elapsed milliseconds. Prefers
// DurationMs (derived at read time from the claims' per-engagement
// telemetry); falls back to CompletedAt-StartedAt; final fallback is
// "now - StartedAt" for the still-running standalone-CLI case. ok=false
// only when the conversation has no duration and no StartedAt.
func ownDurationMs(conv *domain.Conversation) (int, bool) {
	if conv.DurationMs != nil {
		return *conv.DurationMs, true
	}
	if conv.CompletedAt != nil {
		return int(conv.CompletedAt.Sub(conv.StartedAt).Milliseconds()), true
	}
	if !conv.StartedAt.IsZero() {
		return int(time.Since(conv.StartedAt).Milliseconds()), true
	}
	return 0, false
}

// costFromConversation resolves the total cost USD across the conversation's
// whole blueprint run plus the "~" prefix indicator. It sums the authoring
// conversation's own cost with the settled cost of every sibling step in the same
// blueprint_run, so a published review/PR discloses the total spend of
// the multi-step blueprint rather than just the step that authored it.
//
// The authoring conversation's cost prefers conv.TotalCostUSD (canonical, derived
// at read time from the messages ledger) and falls back to recomputing
// from TokenTotalsSystem for the still-running CLI mode. Whenever the
// authoring conversation's settled cost is unavailable — whether we recovered a
// token estimate or the estimate read also failed — the "~" prefix
// flags that the figure is approximate, so a reader never reads a
// sibling-only total as the settled blueprint cost. Sibling steps are
// all terminal by the time a footer is built (the blueprint advanced
// past them), so their total_cost_usd is settled; a failed sibling-cost
// read just omits their contribution rather than blocking the submit.
func costFromConversation(ctx context.Context, conversations db.ConversationStore, orgID, conversationID string, conv *domain.Conversation) (cost float64, prefix string) {
	if conv.TotalCostUSD != nil {
		cost = *conv.TotalCostUSD
	} else {
		// The authoring conversation's own cost is unsettled — the rendered figure
		// is approximate regardless of whether the token-estimate read
		// below succeeds, so flag it now.
		prefix = "~"
		if totals, err := conversations.TokenTotalsSystem(ctx, orgID, conversationID); err == nil {
			model := totals.Model
			if model == "" {
				model = conv.Model
			}
			cost = ai.CalculateCostUSD(model, totals.InputTokens, totals.OutputTokens, totals.CacheReadTokens, totals.CacheCreationTokens)
		}
	}

	if conv.BlueprintRunID != "" {
		if siblings, err := conversations.BlueprintSiblingCostUSDSystem(ctx, orgID, conv.BlueprintRunID, conversationID); err == nil {
			cost += siblings
		}
	}
	return cost, prefix
}

// prettyDurationMs formats a millisecond count as e.g. "42s",
// "2m 13s", or "1h 4m". Hours are the cap — anything longer just
// reads as a big number of hours, which matches the durations we
// actually produce (delegated conversations cap around minutes; an hour is
// already an outlier).
func prettyDurationMs(ms int) string {
	d := time.Duration(ms) * time.Millisecond
	s := int(d.Seconds())
	if s < 60 {
		return fmt.Sprintf("%ds", s)
	}
	m := s / 60
	s = s % 60
	if m < 60 {
		return fmt.Sprintf("%dm %ds", m, s)
	}
	h := m / 60
	m = m % 60
	return fmt.Sprintf("%dh %dm", h, m)
}
