// Package agentmeta builds the disclosure / metadata footer appended
// to agent-published content (review bodies, PR bodies, future surfaces
// like issue comments). Consolidates what used to live as two near-
// duplicate builders in cmd/exec/gh/pr.go and internal/server/
// reviews_handler.go — both did the same job (compute elapsed + cost,
// render markdown footer) but disagreed on the cost source.
//
// The footer discloses Time + Cost only — no model name. A multi-step
// blueprint may run several different models across its steps, so a
// single "Model:" line would be a half-truth (it would name only the
// step that authored the published review/PR); dropping it is the
// honest answer.
//
// Cost is summed across every step of the run's blueprint, not just
// the step that authored the content. The authoring run's own cost
// reads runs.total_cost_usd when populated (the standard path;
// CompleteAgentRun fills it in at run terminal), falling back to a
// token-estimate from RunTokenTotals only while that column is nil —
// the still-running standalone CLI case. The sibling steps' settled
// costs are added on top via BlueprintSiblingCostUSDSystem. With the
// queue-then-approve flow, review/PR submit run AFTER the agent has
// terminated, so the authoring run's column is always populated and
// the estimate fallback is rare.
package agentmeta

import (
	"context"
	"fmt"
	"time"

	"github.com/sky-ai-eng/triage-factory/internal/ai"
	"github.com/sky-ai-eng/triage-factory/internal/db"
	"github.com/sky-ai-eng/triage-factory/internal/domain"
)

// Build returns the markdown footer to append to an agent-authored
// body. kind is the noun in the disclaimer ("review", "PR", future
// surfaces). Always begins with "\n\n---\n" so the caller just
// concatenates: `body + agentmeta.Build(...)`.
//
// Empty runID returns an empty string — there's nothing to disclose
// when no agent run is associated with the content. Callers safely
// concatenate the result; a human running the CLI directly (no
// delegation context) gets their body back unmodified instead of a
// "This was partially generated by AI" lie.
//
// On DB lookup failure with a non-empty runID we fall back to the
// bare branding-only footer rather than blocking the submit — the
// disclosure is still meaningful (a run did exist) even if we
// couldn't render the metrics.
//
// Reads route through the admin-pool `...System` variants (SKY-302).
// Build is a pure read-only formatting utility invoked from contexts
// that don't carry JWT claims — the cmd/exec agent subcommands
// (review/PR submit) and the server's post-approval cleanup paths.
// Wrapping the two-row read in its own synthetic-claims tx just to
// satisfy RLS for a footer would be tx-machinery overhead with no
// visibility benefit (the agent has already proven it can act as
// this run via TRIAGE_FACTORY_RUN_ID → ResolveRunIdentity, and the
// server path is system-driven).
func Build(agentRuns db.AgentRunStore, orgID, runID, kind string) string {
	if runID == "" {
		return ""
	}

	disclaimer := fmt.Sprintf(
		"*This %s was partially generated by AI using [Triage Factory](https://github.com/sky-ai-eng/triage-factory).*",
		kind,
	)
	bare := "\n\n---\n" + disclaimer

	ctx := context.Background()
	run, err := agentRuns.GetSystem(ctx, orgID, runID)
	if err != nil || run == nil {
		return bare
	}

	elapsed := elapsedFromRun(run)
	cost, costPrefix := costFromRun(ctx, agentRuns, orgID, runID, run)

	return fmt.Sprintf(
		"\n\n---\n%s\n\nTime: %s | Cost: %s$%.3f",
		disclaimer, elapsed, costPrefix, cost,
	)
}

// elapsedFromRun returns the human-readable run duration. Prefers the
// stored DurationMs (populated by CompleteAgentRun); falls back to
// CompletedAt-StartedAt; final fallback is "now - StartedAt" for
// still-running standalone-CLI cases. "?" only on a run with no
// StartedAt, which shouldn't happen in practice.
func elapsedFromRun(run *domain.AgentRun) string {
	if run.DurationMs != nil {
		return prettyDurationMs(*run.DurationMs)
	}
	if run.CompletedAt != nil {
		return prettyDurationMs(int(run.CompletedAt.Sub(run.StartedAt).Milliseconds()))
	}
	if !run.StartedAt.IsZero() {
		return prettyDurationMs(int(time.Since(run.StartedAt).Milliseconds()))
	}
	return "?"
}

// costFromRun resolves the total cost USD across the run's whole
// blueprint plus the "~" prefix indicator. It sums the authoring run's
// own cost with the settled cost of every sibling step in the same
// blueprint_run, so a published review/PR discloses the total spend of
// the multi-step blueprint rather than just the step that authored it.
//
// The authoring run's cost prefers run.TotalCostUSD (canonical,
// populated at CompleteAgentRun) and falls back to recomputing from
// RunTokenTotals for the still-running CLI mode. Whenever the
// authoring run's settled cost is unavailable — whether we recovered a
// token estimate or the estimate read also failed — the "~" prefix
// flags that the figure is approximate, so a reader never reads a
// sibling-only total as the settled blueprint cost. Sibling steps are
// all terminal by the time a footer is built (the blueprint advanced
// past them), so their total_cost_usd is settled; a failed sibling-cost
// read just omits their contribution rather than blocking the submit.
func costFromRun(ctx context.Context, agentRuns db.AgentRunStore, orgID, runID string, run *domain.AgentRun) (cost float64, prefix string) {
	if run.TotalCostUSD != nil {
		cost = *run.TotalCostUSD
	} else {
		// The authoring run's own cost is unsettled — the rendered figure
		// is approximate regardless of whether the token-estimate read
		// below succeeds, so flag it now.
		prefix = "~"
		if totals, err := agentRuns.TokenTotalsSystem(ctx, orgID, runID); err == nil {
			model := totals.Model
			if model == "" {
				model = run.Model
			}
			cost = ai.CalculateCostUSD(model, totals.InputTokens, totals.OutputTokens, totals.CacheReadTokens, totals.CacheCreationTokens)
		}
	}

	if run.BlueprintRunID != "" {
		if siblings, err := agentRuns.BlueprintSiblingCostUSDSystem(ctx, orgID, run.BlueprintRunID, runID); err == nil {
			cost += siblings
		}
	}
	return cost, prefix
}

// prettyDurationMs formats a millisecond count as e.g. "42s",
// "2m 13s", or "1h 4m". Hours are the cap — anything longer just
// reads as a big number of hours, which matches the kind of run we
// actually produce (delegated runs cap around minutes; an hour is
// already an outlier).
func prettyDurationMs(ms int) string {
	d := time.Duration(ms) * time.Millisecond
	s := int(d.Seconds())
	if s < 60 {
		return fmt.Sprintf("%ds", s)
	}
	m := s / 60
	s = s % 60
	if m < 60 {
		return fmt.Sprintf("%dm %ds", m, s)
	}
	h := m / 60
	m = m % 60
	return fmt.Sprintf("%dh %dm", h, m)
}
