-- +goose Up
-- An optimistic-concurrency token on the org settings row.
--
-- The org settings save is a read-modify-write over the whole row: a client
-- fetches every field, edits one, and writes them all back. Two admins editing
-- different sections of the same page therefore overwrite each other silently —
-- the second save carries the first's fields as the client last saw them, so
-- the first admin's change is undone with a 200 and nothing to notice. The
-- version turns that into a detectable event: the read hands the client the
-- token it read at, the write requires it, and a write against a stale token is
-- refused so the loser can refetch and re-apply.
--
-- The counter guards the values the settings save writes, not the row's every
-- touch: UpdateSettingsVersioned, the only whole-row writer, bumps it, and so
-- does SetSourceBaseURL, the credential routes' write of a source host the save
-- also sets, when the host it writes differs from the stored one.
-- SetAnthropicKeyRef and SetBedrockCredentialsRef bump it when they change a
-- ref or llm_auth_method: the save cannot write the refs, but it validates
-- llm_auth_method against them. A surgical write to a
-- value the save never touches or checks (SetGitHubCredentialClass,
-- SetLinearWorkspace) leaves it alone, so it never fails an admin's in-flight
-- settings edit over a change that edit could not have undone.
--
-- Day one: local mode is N=1 — a single user on a single machine, with no
-- second admin to race — so existing installs see no behavioural change beyond
-- an extra integer on the wire. The DEFAULT 1 backfills every existing row in
-- place, and a fresh row starts at 1 as well, so an upgraded install and a
-- fresh install are indistinguishable from the first read onwards. No data is
-- rewritten and nothing is dropped.
ALTER TABLE org_settings ADD COLUMN version INTEGER NOT NULL DEFAULT 1;

-- +goose Down
SELECT 'down not supported';
