package domain

import "time"

// EventType defines a specific kind of triage event that can occur. In the
// new model (see docs/data-model-target.md) this maps to the read-only
// `events_catalog` table; only ID/Source/Category/Label/Description are
// persisted. DefaultPriority/Enabled/SortOrder are retained on the struct
// only as stale fields some consumers still read — they no longer round-trip
// to the DB and will be removed when those consumers are rewritten in later
// sub-tickets.
type EventType struct {
	ID              string  `json:"id"`       // e.g. "github:pr:review_requested"
	Source          string  `json:"source"`   // "github", "jira", "system"
	Category        string  `json:"category"` // "pr", "issue", "scoring", "delegation"
	Label           string  `json:"label"`    // Human-readable: "Review Requested"
	Description     string  `json:"description"`
	DefaultPriority float64 `json:"default_priority"` // deprecated — moved to task_rules
	Enabled         bool    `json:"enabled"`          // deprecated — gone from events_catalog
	SortOrder       int     `json:"sort_order"`       // deprecated — moved to task_rules
}

// Event is a single occurrence of an EventType. The persisted columns
// (id, entity_id, event_type, dedup_key, metadata_json) mirror the events
// table in internal/db/db.go; task linkage lives in the task_events
// junction, not here.
//
// TaskID and SourceID are stale compile-shims kept on the struct because
// downstream consumers (auto-delegate, tracker) still reference them. They
// are NOT persisted by RecordEvent — the poller/routing rewrite in SKY-178
// and SKY-179 retires them alongside the consumers.
type Event struct {
	ID           string    `json:"id,omitempty"`        // UUID primary key, caller-supplied (or generated by RecordEvent)
	EventType    string    `json:"event_type"`          // FK to events_catalog.id
	EntityID     *string   `json:"entity_id,omitempty"` // FK to entities.id; nil for system events
	DedupKey     string    `json:"dedup_key"`           // open-set discriminator value (label name, status name); empty when event_type alone is the dedup unit
	MetadataJSON string    `json:"metadata_json"`       // JSON blob with event-specific data, shape per events package
	CreatedAt    time.Time `json:"created_at,omitempty"`

	// Deprecated — stale compile-shims for auto-delegate / tracker until
	// SKY-179 rewires routing to look up tasks via (entity_id, event_type,
	// dedup_key). Not persisted.
	TaskID   string `json:"-"`
	SourceID string `json:"-"`
}

// PollerState stores the last-known snapshot for a source item, used to diff and detect transitions.
type PollerState struct {
	Source    string `json:"source"`
	SourceID  string `json:"source_id"`
	StateJSON string `json:"state_json"`
}

// --- Event Type Taxonomy ---
// These are the canonical event types seeded into the DB on first run.

// GitHub PR events.
//
// Split rule (see docs/data-model-target.md "Splitting events"):
// event types split when a discriminator changes whether/how the situation
// needs attention (conclusion, review type). Attributes that just narrow the
// same situation (reviewer, check name, repo, label) stay as predicate-
// filterable metadata, NOT separate types.
const (
	// Per-check CI events (split on conclusion).
	EventGitHubPRCICheckFailed = "github:pr:ci_check_failed"
	EventGitHubPRCICheckPassed = "github:pr:ci_check_passed"

	// Per-review events (split on review type).
	EventGitHubPRReviewChangesRequested = "github:pr:review_changes_requested"
	EventGitHubPRReviewApproved         = "github:pr:review_approved"
	EventGitHubPRReviewCommented        = "github:pr:review_commented"
	EventGitHubPRReviewDismissed        = "github:pr:review_dismissed"

	// "Someone asked me to review their PR" — singular; reviewer-direction is intrinsic.
	EventGitHubPRReviewRequested = "github:pr:review_requested"

	// "I reviewed someone else's PR" — singular inverse of the per-reviewer events
	// above. Type doesn't matter for triage (it already happened); kept singular.
	EventGitHubPRReviewSubmitted = "github:pr:review_submitted"

	// Labels — per-action, label_name in metadata.
	EventGitHubPRLabelAdded   = "github:pr:label_added"
	EventGitHubPRLabelRemoved = "github:pr:label_removed"

	// PR state events.
	EventGitHubPRMerged         = "github:pr:merged"
	EventGitHubPRClosed         = "github:pr:closed"
	EventGitHubPROpened         = "github:pr:opened"
	EventGitHubPRReadyForReview = "github:pr:ready_for_review"
	EventGitHubPRNewCommits     = "github:pr:new_commits"
	EventGitHubPRConflicts      = "github:pr:conflicts"
	EventGitHubPRMentioned      = "github:pr:mentioned"

	// Deprecated aggregate event types — kept as constants so downstream code
	// compiles during the SKY-174 rewrite. NOT in AllEventTypes(), so they will
	// not be present in events_catalog. Any runtime emission will FK-fail until
	// the downstream emitters are migrated to the per-action types above.
	EventGitHubPRReviewReceived  = "github:pr:review_received"   // → review_changes_requested | review_approved | review_commented | review_dismissed
	EventGitHubPRApproved        = "github:pr:approved"          // → review_approved
	EventGitHubPRChangesReq      = "github:pr:changes_requested" // → review_changes_requested
	EventGitHubPRChangesResolved = "github:pr:changes_resolved"  // → gone (no aggregate transition; close handled inline)
	EventGitHubPRCIPassed        = "github:pr:ci_passed"         // → ci_check_passed
	EventGitHubPRCIFailed        = "github:pr:ci_failed"         // → ci_check_failed
)

// Jira events
const (
	EventJiraIssueAvailable       = "jira:issue:available"
	EventJiraIssueAssigned        = "jira:issue:assigned"
	EventJiraIssueStatusChanged   = "jira:issue:status_changed"
	EventJiraIssueCompleted       = "jira:issue:completed"
	EventJiraIssuePriorityChanged = "jira:issue:priority_changed"
	EventJiraIssueCommented       = "jira:issue:commented"
)

// System events
const (
	EventSystemPollCompleted                 = "system:poll:completed"
	EventSystemScoringCompleted              = "system:scoring:completed"
	EventSystemDelegationCompleted           = "system:delegation:completed"
	EventSystemDelegationFailed              = "system:delegation:failed"
	EventSystemTaskAutoSuspended             = "system:task:auto_suspended"   // deprecated, per-task
	EventSystemPromptAutoSuspended           = "system:prompt:auto_suspended" // per-(entity, prompt) breaker trip
	EventSystemTaskDelegationBlockedSubtasks = "system:task:delegation_blocked_by_subtasks"
)

// AllEventTypes returns the canonical seed catalog for the new per-action
// event model (see docs/data-model-target.md). Only the deprecated aggregate
// constants (EventGitHubPRCIFailed, EventGitHubPRReviewReceived, etc.) are
// deliberately omitted — they exist as Go constants for compile-compat with
// downstream code that hasn't been migrated, but they're not seeded into
// events_catalog so any runtime emission FK-fails until rewritten.
//
// DefaultPriority/Enabled/SortOrder fields on the struct are stale (the
// events_catalog table no longer has those columns). AllEventTypes does not
// populate them, so they remain zero-valued here; SeedEventTypes only
// persists id/source/category/label/description.
func AllEventTypes() []EventType {
	return []EventType{
		// --- GitHub PR — per-action review events (split on review type) ---
		{ID: EventGitHubPRReviewChangesRequested, Source: "github", Category: "pr", Label: "Changes Requested", Description: "A reviewer requested changes on a PR"},
		{ID: EventGitHubPRReviewApproved, Source: "github", Category: "pr", Label: "Review: Approved", Description: "A reviewer approved a PR"},
		{ID: EventGitHubPRReviewCommented, Source: "github", Category: "pr", Label: "Review: Commented", Description: "A reviewer left non-blocking comments on a PR"},
		{ID: EventGitHubPRReviewDismissed, Source: "github", Category: "pr", Label: "Review: Dismissed", Description: "A reviewer dismissed their previous review on a PR"},

		// --- GitHub PR — review request / submission ---
		{ID: EventGitHubPRReviewRequested, Source: "github", Category: "pr", Label: "Review Requested", Description: "Someone requested your review on a PR"},
		{ID: EventGitHubPRReviewSubmitted, Source: "github", Category: "pr", Label: "Review Submitted", Description: "I reviewed someone else's PR (inverse of review_*)"},

		// --- GitHub PR — per-check CI events (split on conclusion) ---
		{ID: EventGitHubPRCICheckFailed, Source: "github", Category: "pr", Label: "CI Check Failed", Description: "A CI check failed on a PR"},
		{ID: EventGitHubPRCICheckPassed, Source: "github", Category: "pr", Label: "CI Check Passed", Description: "A CI check passed on a PR"},

		// --- GitHub PR — labels (open-set discriminator; uses dedup_key=label_name) ---
		{ID: EventGitHubPRLabelAdded, Source: "github", Category: "pr", Label: "Label Added", Description: "A label was added to a PR"},
		{ID: EventGitHubPRLabelRemoved, Source: "github", Category: "pr", Label: "Label Removed", Description: "A label was removed from a PR"},

		// --- GitHub PR — state events ---
		{ID: EventGitHubPRNewCommits, Source: "github", Category: "pr", Label: "New Commits", Description: "A tracked PR has new commits since the last poll"},
		{ID: EventGitHubPRConflicts, Source: "github", Category: "pr", Label: "Merge Conflicts", Description: "A PR has merge conflicts"},
		{ID: EventGitHubPRReadyForReview, Source: "github", Category: "pr", Label: "Ready for Review", Description: "A draft PR was marked ready for review"},
		{ID: EventGitHubPRMentioned, Source: "github", Category: "pr", Label: "Mentioned", Description: "You were @mentioned in a PR"},
		{ID: EventGitHubPROpened, Source: "github", Category: "pr", Label: "PR Opened", Description: "A pull request was opened"},
		{ID: EventGitHubPRMerged, Source: "github", Category: "pr", Label: "PR Merged", Description: "A pull request was merged"},
		{ID: EventGitHubPRClosed, Source: "github", Category: "pr", Label: "PR Closed", Description: "A pull request was closed without merging"},

		// --- Jira ---
		{ID: EventJiraIssueAssigned, Source: "jira", Category: "issue", Label: "Issue Assigned", Description: "Issue was assigned to you"},
		{ID: EventJiraIssueAvailable, Source: "jira", Category: "issue", Label: "Issue Available", Description: "New unassigned issue in pickup queue"},
		{ID: EventJiraIssueStatusChanged, Source: "jira", Category: "issue", Label: "Status Changed", Description: "Issue status changed (uses dedup_key=new_status)"},
		{ID: EventJiraIssuePriorityChanged, Source: "jira", Category: "issue", Label: "Priority Changed", Description: "Issue priority was changed (uses dedup_key=new_priority)"},
		{ID: EventJiraIssueCommented, Source: "jira", Category: "issue", Label: "New Comment", Description: "A new comment was added to an issue"},
		{ID: EventJiraIssueCompleted, Source: "jira", Category: "issue", Label: "Issue Completed", Description: "Issue was marked as done"},

		// --- System events (never user-visible) ---
		{ID: EventSystemPollCompleted, Source: "system", Category: "poll", Label: "Poll Complete", Description: "A poller finished a cycle"},
		{ID: EventSystemScoringCompleted, Source: "system", Category: "scoring", Label: "Scoring Complete", Description: "AI scoring finished for a task"},
		{ID: EventSystemDelegationCompleted, Source: "system", Category: "delegation", Label: "Delegation Complete", Description: "Agent delegation run completed"},
		{ID: EventSystemDelegationFailed, Source: "system", Category: "delegation", Label: "Delegation Failed", Description: "Agent delegation run failed"},
		{ID: EventSystemPromptAutoSuspended, Source: "system", Category: "delegation", Label: "Prompt Auto-suspended", Description: "Per-(entity, prompt) breaker tripped after repeated failures"},
		{ID: EventSystemTaskDelegationBlockedSubtasks, Source: "system", Category: "delegation", Label: "Delegation Blocked: Subtasks", Description: "Auto-delegation skipped because parent has open subtasks"},
	}
}
